services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile/frontend.dockerfile
    ports:
      - 3000:3000
    working_dir: /app
    environment:
      - VITE_BACKEND_HOST=http://localhost:3001
    restart: always

  backend:
    build:
      context: .
      dockerfile: dockerfile/backend.dockerfile
    environment:
      - PORT=3001
      - PG_USER=postgres
      - PG_HOST=db
      - PG_DB=postgres
      - PG_PASSWORD=example
      - PG_PORT=5432
      - REINIT_DB=false
      - FRONTEND_URL=http://localhost:3000
      - GEMINI_API_KEY=...
    ports:
      - 3001:3001
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      PGUSER: postgres # needed b/c psql and pg_isready use different env vars
      POSTGRES_PASSWORD: example
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
